export enum TipoEquipoImpresion {
  INYECCION_TINTA = 'INYECCION TINTA',
  LASER = 'LASER',
  MULTIFUNCIONAL = 'MULTIFUNCIONAL',
  TERMICA = 'TERMICA',
  PLOTTER = 'PLOTTER',
  MATRICIAL = 'MATRICIAL',
  OFFSET = 'OFFSET',
  FLEXOGRAFICA = 'FLEXOGRAFICA',
  ROTATIVA = 'ROTATIVA',
}